-- ============================================================================
-- MBU CAR SALES — SCHEMA v10: INVOICES
-- ----------------------------------------------------------------------------
-- Run after the others (any time after schema.sql). Safe to run more than
-- once. Adds only: two tables. No existing table, column or rule changes.
--
--   · invoices      every invoice, receipt and instalment agreement made in
--                   the admin app: who it's for, the car, the figures, the
--                   terms, any signatures, and when it was sent. Numbered
--                   MBU-1001, MBU-1002… in the order they're first saved.
--   · app_settings  small shared settings, so both phones agree. Today just
--                   'invoice': who sells (names and numbers), the business
--                   details printed at the top, VAT, how to pay.
--
-- Private. Both are admin-only: the public key can't read or write either,
-- and nothing here is in cars_public. Invoices hold customers' names,
-- addresses, phone numbers and email addresses, so they must stay that way.
--
-- Most of an invoice lives in one `data` column (jsonb), because every part
-- of it can be changed per invoice (extra lines, part exchange, payments,
-- an instalment plan, each term's wording). The handful of columns beside it
-- are the ones the app lists and searches by.
--
-- Keep them: HMRC expects a limited company's sales records kept for six
-- years from the end of the financial year they relate to. "Void" an invoice
-- made in error rather than deleting it, so the numbers stay unbroken.
-- ============================================================================

create table if not exists public.invoices (
  id          uuid primary key default gen_random_uuid(),
  number      integer generated by default as identity (start with 1001) unique,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now(),

  kind        text not null default 'paid'
              check (kind in ('paid','deposit','balance','instalments','trade','purchase','general')),
  status      text not null default 'issued'
              check (status in ('draft','issued','void')),
  issue_date  date not null default current_date,

  car_id      uuid references public.cars(id) on delete set null,
  registration text,                 -- copied from the car at the time, for searching
  customer_name text,

  total       numeric(10,2),         -- what the customer owes for it all
  paid        numeric(10,2),         -- received so far
  balance     numeric(10,2),         -- still to come

  data        jsonb not null default '{}'::jsonb,
  sent_at     timestamptz            -- the last time it was shared or emailed
);

comment on table public.invoices is
  'Invoices, receipts and instalment agreements from the admin app. Admin-only: holds customer contact details.';
comment on column public.invoices.data is
  'Everything else on the invoice: vehicle, customer, seller, extras, part exchange, payments, plan, terms, notes, signatures, send history.';

create index if not exists invoices_car_idx on public.invoices (car_id) where car_id is not null;
create index if not exists invoices_created_idx on public.invoices (created_at desc);

alter table public.invoices enable row level security;

drop policy if exists "Admins manage invoices" on public.invoices;
create policy "Admins manage invoices" on public.invoices
  for all to authenticated
  using (public.is_admin())
  with check (public.is_admin());

revoke all on public.invoices from anon;
grant select, insert, update, delete on public.invoices to authenticated;
grant usage on sequence public.invoices_number_seq to authenticated;

-- ---------------------------------------------------------------------------

create table if not exists public.app_settings (
  key         text primary key,
  value       jsonb not null default '{}'::jsonb,
  updated_at  timestamptz not null default now()
);

comment on table public.app_settings is
  'Small settings shared between the admin phones. Admin-only.';

alter table public.app_settings enable row level security;

drop policy if exists "Admins manage settings" on public.app_settings;
create policy "Admins manage settings" on public.app_settings
  for all to authenticated
  using (public.is_admin())
  with check (public.is_admin());

revoke all on public.app_settings from anon;
grant select, insert, update, delete on public.app_settings to authenticated;

-- ----------------------------------------------------------------------------
-- Check it worked (both should run without an error, and return no rows):
--   select number, kind, customer_name from public.invoices limit 1;
--   select key from public.app_settings limit 1;
--
-- And that the public can't see them: in a new tab, as the publishable key,
--   /rest/v1/invoices?select=*   → should return an error or an empty list.
--
-- Undo (deletes every invoice; download them first):
--   drop table if exists public.invoices;
--   drop table if exists public.app_settings;
-- ----------------------------------------------------------------------------
